name: 'TYPO3 Ter Uploader'
description: 'GitHub Action that helps you upload your Extensions to TER'
branding:
  icon: upload
  color: orange
inputs:
  api-token: # id of input
    description: 'Your TYPO3 API Token - Use github.secrets'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api-token }}